[package]
name = "rust-mw"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2.5"
dirs = "6.0"

anyhow = "1.0"

rand = "0.9.2"

aes = "0.8.4"
ctr = "0.9.2"
cipher = "0.4.4"
base64 = "0.22.1"
sysinfo = "0.37.2"
chrono = "0.4.42"

# Nur für Unix-Systeme (Linux/MacOS) für den Deamon Mode
[target.'cfg(unix)'.dependencies]
daemonize = "0.5"
